_target_: src.architectures.huggingface_architecture.HuggingFaceArchitecture

model:
  _target_: src.architectures.models.huggingface_model.HuggingFaceModel
  pretrained_model_name: ${pretrained_model_name}
  is_preprocessed: ${is_preprocessed}
  custom_data_encoder_path: ${custom_data_encoder_path}
  merged_model_path: ${merged_model_path}
  precision: ${precision}
  mode: ${mode}
  quantization_type: ${quantization_type}
  quantization_config:
    _target_: transformers.BitsAndBytesConfig
    load_in_4bit: ${quantization_config.load_in_4bit}
    bnb_4bit_quant_type: ${quantization_config.bnb_4bit_quant_type}
    bnb_4bit_use_double_quant: ${quantization_config.bnb_4bit_use_double_quant}
    bnb_4bit_compute_dtype: ${quantization_config.bnb_4bit_compute_dtype}
  peft_type: ${peft_type}
  peft_config:
    _target_: peft.LoraConfig
    r: ${peft_config.r}
    lora_alpha: ${peft_config.lora_alpha}
    target_modules: ${peft_config.target_modules}
    lora_dropout: ${peft_config.lora_dropout}
    bias: ${peft_config.bias}
    task_type: ${peft_config.task_type}

pretrained_model_name: ${pretrained_model_name}
is_preprocessed: ${is_preprocessed}
custom_data_encoder_path: ${custom_data_encoder_path}
strategy: ${strategy}
lr: ${lr}
weight_decay: ${weight_decay}
half_period: ${half_period}
eta_min_rate: ${eta_min_rate}
interval: step
options: ${options}
target_max_length: ${target_max_length}
target_min_length: ${target_min_length}
per_device_save_path: ${per_device_save_path}
target_column_name: ${target_column_name}
