_target_: src.datasets.huggingface_dataset.UpStageDialoguesDataset
data_path: ${connected_dir}/data
split: ${split.train}
is_causal: ${is_causal}
is_preprocessed: ${is_preprocessed}
data_column_name: ${data_column_name}
prompt_column_name: ${prompt_column_name}
target_column_name: ${target_column_name}
num_devices: ${devices}
batch_size: ${batch_size}
pretrained_model_name: ${pretrained_model_name}
custom_data_encoder_path: ${custom_data_encoder_path}
data_max_length: ${data_max_length}
target_max_length: ${target_max_length}
