_target_: src.datasets.huggingface_dataset.UpStageDialoguesDataset
data_path: ${connected_dir}/data
split: ${split.train}
seed: ${seed}
target_column_name: ${target_column_name}
num_devices: ${devices}
batch_size: ${batch_size}
pretrained_model_name: ${pretrained_model_name}
text_max_length: ${text_max_length}
