model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: ${monitor}
  mode: ${tracking_direction}
  save_top_k: ${patience}
  save_last: True
  verbose: True
  dirpath: ${connected_dir}/checkpoints/${model_name}/${dataset_name}/${is_tuned}/${strategy}/${save_detail}
  filename: epoch{epoch}
  auto_insert_metric_name: False

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: ${monitor}
  mode: ${tracking_direction}
  patience: ${patience}
  min_delta: ${min_delta}

model_summary:
  _target_: lightning.pytorch.callbacks.RichModelSummary
  max_depth: -1

rich_progress_bar:
